[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mega-vit"
version = "0.0.4"
description = "mega-vit - Pytorch"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Kye Gomez", email = "kye@apac.ai"}
]
keywords = [
    "artificial intelligence",
    "deep learning",
    "optimizers",
    "Prompt Engineering"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6"
]
requires-python = ">=3.6"
dependencies = [
    "torch",
    "einops",
]
